version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.6'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
        - '3306:3306'
  moodle:
    image: 'bitnami/moodle:4.1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle  
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      
      # Plus Cấu hình email
      - MOODLE_SMTP_HOST=smtp.gmail.com
      - MOODLE_SMTP_PORT=587
      - MOODLE_SMTP_USER=noreply.enow@gmail.com
      - MOODLE_SMTP_PASSWORD=sndashmyulfxeuvp
      - MOODLE_SMTP_PROTOCOL=tls
    ports:
      - '8011:80'
      #- '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local